steps:
  - label: smith-client
    plugins:
      - docker-compose#v3.0.3:
          run: haskell
          config: '.buildkite/docker-compose.yml'
    command:
      - 'aws s3 cp s3://smith-artefacts/cache/smith-client-cache.tar.gz smith-client-cache.tar.gz || true'
      - 'tar xfz openssh-protcol-cache.tar.gz -C /root || true'
      - 'rm -f openssh-protcol-cache.tar.gz'
      - 'mafia update'
      - 'mafia build'
      - 'tar cfz smith-client-cache.tar.gz -C /root .mafia .cabal'
      - 'aws s3 cp smith-client-cache.tar.gz s3://smith-artefacts/cache/smith-client-cache.tar.gz'
      - 'mafia test'
